name: Auto Pull Request
on:
  push:
    branches:
      - preproduction

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: preproduction
          destination_branch: develop
          pr_title: "Automated PR: Changes from branch X to Y"
          pr_body: "This is an automated pull request to merge changes from branch X to Y."
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
